INSERT INTO permission_bundles (permission_bundle_id, role_id, bundle_code, permitted_actions, active_flag)
VALUES (
  '99999999-9999-9999-9999-999999999999',
  '44444444-4444-4444-4444-444444444444',
  'PRIVACY_FULL',
  '["PRIVACY_CONSENT_RECORD", "PRIVACY_CONSENT_WITHDRAW", "PRIVACY_NOTICE_CREATE", "PRIVACY_NOTICE_APPROVE", "PRIVACY_NOTICE_PUBLISH", "PRIVACY_NOTICE_WITHDRAW", "PRIVACY_PREFERENCE_SET", "PRIVACY_PURPOSE_CREATE", "PRIVACY_PURPOSE_PUBLISH", "PRIVACY_ACTIVITY_CREATE", "PRIVACY_ACTIVITY_VALIDATE", "PRIVACY_ACTIVITY_SUBMIT", "PRIVACY_ACTIVITY_APPROVE", "PRIVACY_ACTIVITY_ACTIVATE", "PRIVACY_ACTIVITY_SUSPEND", "PRIVACY_ACTIVITY_RESUME", "PRIVACY_ACTIVITY_RETIRE"]'::jsonb,
  true
)
ON CONFLICT (role_id, bundle_code) DO UPDATE
SET permitted_actions = EXCLUDED.permitted_actions;
